# action.yml
name: 'as3_schema_validator'
description: 'Validates AS3 declaration against schema'
branding:
  icon: 'check-square'
inputs:
  declaration:
    description: 'AS3 declaration file'
    required: true
    default: 'as3.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.declaration }}
