on: [push]

jobs:
  as3schema:
    name: Validate AS3 Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate AS3 Schema
        id: hello
        uses: ./
        with:
          declaration: 'as3.json'